# Site settings
title: Pria Purnama
email: dudewithmessyhair@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Versatile engineering manager with over a decade of experience in tech and product management.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://priapurnama.github.io/" # the base hostname & protocol for your site
twitter_username: anima
github_username:  priapurnama

# Build settings
markdown: kramdown

timezone: Asia/Jakarta
encoding: utf-8
highlighter: rouge